version: "3.8"

services:
  wanderer-kills:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4004
    ports:
      - "4004:4004"
    command: ["bin/wanderer_kills", "start"] 